version: "3.6"

services:
  app:
    container_name: ${CONTAINER_PREFIX}.app
    build: docker/app
    volumes:
      - .:/app
    ports:
      - ${BIND_EXPRESS_PORT}:${EXPRESS_PORT}

  mongodb:
    container_name: ${CONTAINER_PREFIX}.mongodb
    image: mongo
    volumes:
      - mongodb:/data/db
    ports:
      - ${BIND_DB_PORT}:27017

volumes:
  mongodb: {}
